### ISSUE TITLE
DomainEvents should be immutable classes (but cannot be with serialization implementation)

### ISSUE THREAD

**Issue by darbio** [sapiens/DominoEventStore#2]
From the [dotnet ddd docs](https://github.com/dotnet/docs/blob/master/docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/domain-events-design-implementation.md#implementing-domain-events)

> An important characteristic of events is that since an event is something that happened in the past, it should not change. Therefore it must be an immutable class.

At the moment, the JSON deserializer for this project won't deserialize to private/read-only properties of the domain event as it uses the JSON.net default deserializer contract and the event does not follow a convention that JSON.net understands (making the domain event depend upon JSON.net is leakage of implementation into domain model and using the JSON.net constructor pattern introduces a buggy surface if the constructor does not include all of the properties).

For example, the following will deserialize without setting the `Location` property:

```
    public class CreatedEvent : DomainEvent
    {
        public string Location { get; }

        public CreatedEvent(string location, Foo bar): base(bar) {
            this.Location = location;
        }
    }
```

Obviously, having a public set method solves this, however it makes the DomainEvent mutable which is not correct behaviour.

See [here](https://danielwertheim.se/json-net-private-setters/) for a possible solution.

**Comment by sapiens** [comment]
> Therefore it must be an immutable class.

Very strong words :) .  I disagree with it and seeing your source, even more :)) . When it comes to DDD/ES,CQRS  Microsoft is not the most reliable source. Sad but true. They are good at low-middle level technical stuff, but they (of course not all, but as an average) kinda suck at high level design and dissociating between recipes and principles. In a nutshell, they are too coupled to an actual implementation, instead of going for the principles.

About event mutability, that's for the business to remember that we don't change the past (with exceptions). private setters are just a gimmick, immutability of a domain event has nothing to do with private/public setters.

I feel that we probably disagree on this topic, however I've got to this point after almost 10 years of doing ES, so things will remain as they are. But feel free to fork it, more choices are good!

**Comment by darbio** [comment]
> About event mutability, that's for the business to remember that we don't change the past

Seems like a recipe for disaster if you're working in a team of more than 1 person touching the code! In my experience, if a developer can set a property, they probably  will do at some point once the theoretical rule is forgotten. 

If you don't like Microsoft's implementation, maybe you could be swayed by [Martin Fowler](https://martinfowler.com/eaaDev/EventSourcing.html) or [Vaugn Vernon's](https://github.com/VaughnVernon/IDDD_Samples/blob/master/iddd_identityaccess/src/main/java/com/saasovation/identityaccess/domain/model/access/GroupAssignedToRole.java) implementations of immutable domain events (both unarguable heavy weights in the ES/DDD world). Both implementations use private fields/setters to provide immutability.

**Comment by sapiens** [comment]
I have the feeling Vaughn Vernon wouldn't care that much about immutable classes. Sure, they are better but a **must** , they're not. Anyway, it's not my first time discussing these things over the years and you already know my conclusion.
